var s = document.location.pathname.split('/');
var example = s[s.length - 1].split('.')[0];

require({
    baseUrl: '.',
    paths: {
        domReady: '../cesium/ThirdParty/requirejs-2.1.20/domReady',
        Cesium: '../cesium/Source'
    }
}, [ 'Cesium/Core/Cartesian2', 'Cesium/Core/Cartesian3', 'Cesium/Core/Cartographic', 'Cesium/Core/CesiumTerrainProvider', 'Cesium/Core/CircleGeometry', 'Cesium/Core/CircleOutlineGeometry', 'Cesium/Core/clone', 'Cesium/Core/ColorGeometryInstanceAttribute', 'Cesium/Core/Color', 'Cesium/Core/Credit', 'Cesium/Core/defaultValue', 'Cesium/Core/defined', 'Cesium/Core/Ellipsoid', 'Cesium/Core/Event', 'Cesium/Core/GeographicTilingScheme', 'Cesium/Core/GeometryInstanceAttribute', 'Cesium/Core/GeometryInstance', 'Cesium/Core/Geometry', 'Cesium/Core/IntersectionTests', 'Cesium/Core/Intersect', 'Cesium/Core/JulianDate', 'Cesium/Core/KeyboardEventModifier', 'Cesium/Core/loadImage', 'Cesium/Core/loadWithXhr', 'Cesium/Core/Math', 'Cesium/Core/Matrix3', 'Cesium/Core/Matrix4', 'Cesium/Core/PolygonGeometry', 'Cesium/Core/PolygonOutlineGeometry', 'Cesium/Core/PolylineGeometry', 'Cesium/Core/Quaternion', 'Cesium/Core/Ray', 'Cesium/Core/Rectangle', 'Cesium/Core/ScreenSpaceEventHandler', 'Cesium/Core/ScreenSpaceEventType', 'Cesium/Core/TaskProcessor', 'Cesium/Core/TerrainProvider', 'Cesium/Core/TilingScheme', 'Cesium/Core/Transforms', 'Cesium/Core/WebMercatorTilingScheme', 'Cesium/DataSources/DataSourceCollection', 'Cesium/DataSources/DataSourceDisplay', 'Cesium/DataSources/DataSource', 'Cesium/DataSources/KmlDataSource', 'Cesium/Scene/Appearance', 'Cesium/Scene/BillboardCollection', 'Cesium/Scene/Billboard', 'Cesium/Scene/CameraEventType', 'Cesium/Scene/Camera', 'Cesium/Scene/Globe', 'Cesium/Scene/GroundPrimitive', 'Cesium/Scene/HeightReference', 'Cesium/Scene/HorizontalOrigin', 'Cesium/Scene/Imagery', 'Cesium/Scene/ImageryLayerCollection', 'Cesium/Scene/ImageryLayer', 'Cesium/Scene/ImageryProvider', 'Cesium/Scene/LabelCollection', 'Cesium/Scene/Label', 'Cesium/Scene/LabelStyle', 'Cesium/Scene/MaterialAppearance', 'Cesium/Scene/Material', 'Cesium/Scene/PerInstanceColorAppearance', 'Cesium/Scene/Polygon', 'Cesium/Scene/Polyline', 'Cesium/Scene/PolylineMaterialAppearance', 'Cesium/Scene/PrimitiveCollection', 'Cesium/Scene/Primitive', 'Cesium/Scene/RectanglePrimitive', 'Cesium/Scene/Scene', 'Cesium/Scene/SkyAtmosphere', 'Cesium/Scene/VerticalOrigin' ],
   function(Cartesian2, Cartesian3, Cartographic, CesiumTerrainProvider, CircleGeometry, CircleOutlineGeometry, clone, ColorGeometryInstanceAttribute, Color, Credit, defaultValue, defined, Ellipsoid, Event, GeographicTilingScheme, GeometryInstanceAttribute, GeometryInstance, Geometry, IntersectionTests, Intersect, JulianDate, KeyboardEventModifier, loadImage, loadWithXhr, Math, Matrix3, Matrix4, PolygonGeometry, PolygonOutlineGeometry, PolylineGeometry, Quaternion, Ray, Rectangle, ScreenSpaceEventHandler, ScreenSpaceEventType, TaskProcessor, TerrainProvider, TilingScheme, Transforms, WebMercatorTilingScheme, DataSourceCollection, DataSourceDisplay, DataSource, KmlDataSource, Appearance, BillboardCollection, Billboard, CameraEventType, Camera, Globe, GroundPrimitive, HeightReference, HorizontalOrigin, Imagery, ImageryLayerCollection, ImageryLayer, ImageryProvider, LabelCollection, Label, LabelStyle, MaterialAppearance, Material, PerInstanceColorAppearance, Polygon, Polyline, PolylineMaterialAppearance, PrimitiveCollection, Primitive, RectanglePrimitive, Scene, SkyAtmosphere, VerticalOrigin) {
      window.Cesium = {Cartesian2: Cartesian2, Cartesian3: Cartesian3, Cartographic: Cartographic, CesiumTerrainProvider: CesiumTerrainProvider, CircleGeometry: CircleGeometry, CircleOutlineGeometry: CircleOutlineGeometry, clone: clone, ColorGeometryInstanceAttribute: ColorGeometryInstanceAttribute, Color: Color, Credit: Credit, defaultValue: defaultValue, defined: defined, Ellipsoid: Ellipsoid, Event: Event, GeographicTilingScheme: GeographicTilingScheme, GeometryInstanceAttribute: GeometryInstanceAttribute, GeometryInstance: GeometryInstance, Geometry: Geometry, IntersectionTests: IntersectionTests, Intersect: Intersect, JulianDate: JulianDate, KeyboardEventModifier: KeyboardEventModifier, loadImage: loadImage, loadWithXhr: loadWithXhr, Math: Math, Matrix3: Matrix3, Matrix4: Matrix4, PolygonGeometry: PolygonGeometry, PolygonOutlineGeometry: PolygonOutlineGeometry, PolylineGeometry: PolylineGeometry, Quaternion: Quaternion, Ray: Ray, Rectangle: Rectangle, ScreenSpaceEventHandler: ScreenSpaceEventHandler, ScreenSpaceEventType: ScreenSpaceEventType, TaskProcessor: TaskProcessor, TerrainProvider: TerrainProvider, TilingScheme: TilingScheme, Transforms: Transforms, WebMercatorTilingScheme: WebMercatorTilingScheme, DataSourceCollection: DataSourceCollection, DataSourceDisplay: DataSourceDisplay, DataSource: DataSource, KmlDataSource: KmlDataSource, Appearance: Appearance, BillboardCollection: BillboardCollection, Billboard: Billboard, CameraEventType: CameraEventType, Camera: Camera, Globe: Globe, GroundPrimitive: GroundPrimitive, HeightReference: HeightReference, HorizontalOrigin: HorizontalOrigin, Imagery: Imagery, ImageryLayerCollection: ImageryLayerCollection, ImageryLayer: ImageryLayer, ImageryProvider: ImageryProvider, LabelCollection: LabelCollection, Label: Label, LabelStyle: LabelStyle, MaterialAppearance: MaterialAppearance, Material: Material, PerInstanceColorAppearance: PerInstanceColorAppearance, Polygon: Polygon, Polyline: Polyline, PolylineMaterialAppearance: PolylineMaterialAppearance, PrimitiveCollection: PrimitiveCollection, Primitive: Primitive, RectanglePrimitive: RectanglePrimitive, Scene: Scene, SkyAtmosphere: SkyAtmosphere, VerticalOrigin: VerticalOrigin};
      window.setTimeout(function() {
        var script = document.createElement('script');
        script.setAttribute('type', 'text/javascript');
        script.setAttribute('src', document.location.origin + '/examples/' + example + '.js');
        document.getElementsByTagName('body')[0].appendChild(script);
      }, 50);
  }
);
